# Continuous Integration workflow
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'            # matches every branch
  #    - '!development'  # excludes development
  #    - '!master'       # excludes master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  #pull_request:
  #  branches:
  #    - 'development'   # includes development
  #    - 'master'        # includes master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build & test job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build -- --prod --base-href ./
    
    #Run tests
    - name: Test
      run: npm test -- --configuration=ci
    - name: E2E
      run: npm run e2e -- --configuration=ci
  # Dev deployment job
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'development' }}
  # Pro deployment job
  deploy-pro:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'master' }}
    steps:
      - name: Tag release version
        run: ?
      - name: Create release package
        run: ?
      - name: Deploy on prod server
        run: ?